site:
  title: ownCloud Documentation
  url: https://doc.owncloud.com

content:
  sources:
  - url: https://github.com/owncloud/docs.git
    branches:
    - master
    - 10.1
    - 10.0
  - url: https://github.com/owncloud/android.git
    branches:
    - master-antora
    start_path: docs/
  - url: https://github.com/owncloud/ios.git
    branches:
    - master-antora
    start_path: docs/
  - url: https://github.com/owncloud/client.git
    branches:
    - master-antora
    start_path: docs/
  - url: https://github.com/owncloud/branded_clients.git
    branches:
    - master-antora

ui:
  output_dir: assets
  bundle:
    url: https://minio.owncloud.com/documentation/ui-bundle.zip
    snapshot: true

output:
  clean: true
  dir: public

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
